server:
  port: ${SERVER_PORT}

spring:
  application:
    name: discovery-server

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: ${EUREKA_SELF_PRESERVATION}
    eviction-interval-timer-in-ms: ${EUREKA_EVICTION_INTERVAL_MS}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: never

  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: ${TRACING_SAMPLE_PROBABILITY}
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT}

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{correlationId:-},%X{traceId:-},%X{spanId:-}]"
